spring:
  datasource:
    read:
      password: 1234
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/test
      username: root
    write:
      password: 1234
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/test
      username: root
  jpa:
    properties:
      database: mysql
      database-platform: mysql
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL57Dialect
      show-sql: true
