spring:
  mail:
    host: smtp.qq.com
    # smtp默认端口:465或587
    port: 465
    username: from-eamil@qq.com
    # 邮件设置开启smtp获取授权码
    password: lfpvbfmfadyzbajg
    default-encoding: utf-8
    properties:
      mail:
        # 控制台打印日志
        debug: true
        smtp:
          # 传输加密
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  # 配置邮件告警服务启动上下线
  boot:
    admin:
      notify:
        mail:
          from: from-eamil@qq.com
          to: to-email@outlook.com
          # 空白表示启动与关闭都发送,默认是忽略启动通知: UNKNOWN to UP.(服务关闭是UP to OFFLINE)
          ignore-changes:
            - UNKNOWN:UP
            - UP:OFFLINE
