server:
  port: 8092
# 服务名
spring:
  application:
    name: zuul-provider
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
